# Generated by Django 5.2.6 on 2025-09-06 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productivity_app', '0002_alter_task_assigned_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
